Estimate runtime refactoring
TomWhitwell/SlowMovie pull request #117
Opened 2022-02-22 11:55 UTC by yippieyaray

This is my refactoring of the estimate_runtime function to fix "Runtime estimation problem #115 (https://github.com/TomWhitwell/SlowMovie/issues/115)"
It's not my quick fix from yesterday. I remove all unnecessary loops and recursions as well.

2022-02-22 14:05 UTC, robweber commented
The changes make sense to me. I ran the new function in it's own file with a variety of different increments and frame values without issue. The only spot I can find this function is called is when the [remaining time is logged](https://github.com/TomWhitwell/SlowMovie/blob/main/slowmovie.py#L378). For it's intended purpose I think making it as lightweight as possible is a good change. 

@qubist - I think you may have originally added this function. Any thoughts?

2022-02-24 03:26 UTC, qubist commented
If merged, this closes #115

2022-02-24 03:35 UTC, qubist commented on slowmovie.py
> +# output value: "d[ay]", "h[our]", "m[inute]", "s[econd]", false; omit for an automatic guess
```suggestion

```

2022-02-24 03:37 UTC, qubist requested changes
This is a very elegant refactor of the function! Thank you for your contribution, @yippieyaray. I'm ready to approve changes after the comment line I mentioned is removed.

2022-03-03 19:18 UTC, qubist commented
Thanks for moving forward with this, @missionfloyd !

2022-03-03 19:18 UTC, qubist approved these changes
I'm ready for this to be merged

2022-03-04 00:31 UTC, merged