README Update for Logging Changes
TomWhitwell/SlowMovie pull request #59
Opened 2021-04-12 19:02 UTC by robweber

Updated the README pieces that mention logging to reflect the merge of the new logging code.

2021-04-13 06:02 UTC, missionfloyd commented on README.md
>  (slowmovie.conf). Config file syntax allows: key=value, flag=true,
```suggestion
Arguments can also be set in a config file (slowmovie.conf). Config
file syntax allows: key=value, flag=true,
```
I tried using short arguments in the config file, and it works. (I would've aligned the rest of this paragraph, but GitHub doesn't allow commenting on collapsed lines.)

2021-04-14 21:24 UTC, qubist approved these changes

2021-04-14 21:25 UTC, qubist commented
Looks great, I think should be merged quick so it's there and easy to see for folks!

2021-04-14 23:43 UTC, qubist requested changes

2021-04-14 23:43 UTC, qubist commented on README.md
> +                         logfile (default: INFO)
```suggestion
  -o {DEBUG,INFO,WARNING,ERROR,CRITICAL}, --loglevel {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                         minimum importance-level of messages displayed and
                         saved to the logfile (default: INFO)
```

Updated for new message re: 8f411a8729b4167d4496599b401717b6728a99d4

2021-04-15 12:58 UTC, merged